# Generated by Django 3.0.3 on 2020-04-24 04:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_v2', '0002_auto_20200420_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Visitors', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('text', models.TextField()),
                ('create_time', models.DateTimeField(default=datetime.datetime(2020, 4, 24, 4, 2, 18, 557764, tzinfo=utc))),
                ('psot', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_v2.Post')),
            ],
            options={
                'db_table': 'Comment',
                'ordering': ['-create_time'],
            },
        ),
    ]
