# Generated by Django 3.0.3 on 2020-04-24 04:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 4, 8, 34, 643230, tzinfo=utc)),
        ),
    ]
