# Generated by Django 3.0.3 on 2020-04-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='src',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
